### PR TITLE
Added a Blog on CryptoCurrency And BlockChain

### PR DESCRIPTION
**Pull request by Prasanna1717**
### Description
I created a Blog of my views on Cryptography and Blockchain Technology as my Open-Source Contribution.
 
### Issues Resolved
It creates Awareness and Ideas for People, about what is Crypto and How it works, which will be soon the 12th Sector of S&P. 

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by dtaivpp** [comment]
@Prasanna1717 we will not be merging this content as it contains copyrighted material which is a violation of our DCO.

**Comment by Prasanna1717** [comment]
> @Prasanna1717 we will not be merging this content as it contains copyrighted material which is a violation of our DCO.  

Sorry for this inconvenience, I'll review and update the issues since some quotes were taken from books it deals with copyright issues..

**Comment by krisfreedain** [comment]
@Prasanna1717 it also is not relevant information to share with the OpenSearch community

**Comment by Prasanna1717** [comment]
> @Prasanna1717 it also is not relevant information to share with the OpenSearch community

Oh i thought general blog , sorry for it...

**Pull request closed without merging**
