### PR TITLE
Clarify that Get Started is how to download OpenSearch

### PR DESCRIPTION
**Pull request by peternied**
### Description
Existing website makes it hard to know where OpenSearch can be downloaded from, so updating the text.  Note, its kind of wordy, but I am open to suggestions.

#### Before
image

#### After
image

image

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by stockholmux** [comment]
Let's continue discussion on the forums:

https://discuss.opendistrocommunity.dev/t/download-or-get-started-on-opensearch-org/7317/5?u=searchymcsearchface

**Comment by peternied** [comment]
@stockholmux closing out this pull request that is 2 months old so there is one less thing for me to track, doesn't seem to be movement on this issue.

**Comment by stockholmux** [comment]
@peternied I'm just now getting a chance to work on this part, so reopening.

**Comment by peternied** [comment]
Hi! Any progress on this pull request?

**Review by stockholmux — APPROVED** [review]
I'm going to approve these, but it'll likely have a few tweaks before production.

**Pull request merged**
