### PR TITLE
adding Oracle Cloud logo

### PR DESCRIPTION
**Pull request by dmitrypol**
### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by stockholmux** [comment]
@dmitrypol That's a familiar face - we should catch up! Glad to see you here. 

Humm. Looks like your DCO check failed. Signing the commit is done by doing a `git commit -s -m "<your commit message>"` It adds something like `Signed-off-by: name <email@example.com>` to the commit. Also, here is a great guide for fixing DCO issues: https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md

In this case you'll need to squash the two commits into one and do the sign off thing as described above.

@elfisher could you take it for at test drive locally to see if it look ok?

**Comment by dmitrypol** [comment]
thanks @stockholmux.  Updated the PR.

**Comment by elfisher** [comment]
> @elfisher could you take it for at test drive locally to see if it look ok?

Yeah. I was just in the middle of that :)

**Review by elfisher — APPROVED** [review]
LGTM

**Pull request merged**
