### PR TITLE
Adding Seacom as Partner

### PR DESCRIPTION
**Pull request by anteos**
### Description
I'm asking to add Seacom as a Partner
 
### Check List
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by anteos** [comment]
I've rebased and pushed, is it ok?

Schermata 2022-06-10 alle 18 38 57

**Comment by krisfreedain** [comment]
@anteos - it looks like DCO is still failing. Please update your commit with --signoff.

**Comment by anteos** [comment]
> @anteos - it looks like DCO is still failing. Please update your commit with --signoff.

@krisfreedain - I've added the --signoff info; can you review the PR?

**Review by krisfreedain — APPROVED** [review]
thanks @anteos! Looks good

**Pull request merged**
