### PR TITLE
Adds new partner - Highlight

### PR DESCRIPTION
**Pull request by haroonchoudery**
### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by krisfreedain** [comment]
Hello @haroonchoudery - so glad to see this PR! The repo requires a DCO sign off ([a few tips on retroactively applying a sign off](https://github.com/src-d/guide/blob/9171d013c648236c39faabcad8598be3c0cf8f56/developer-community/fix-DCO.md)) - could you add that?

**Comment by haroonchoudery** [comment]
> Hello @haroonchoudery - so glad to see this PR! The repo requires a DCO sign off ([a few tips on retroactively applying a sign off](https://github.com/src-d/guide/blob/9171d013c648236c39faabcad8598be3c0cf8f56/developer-community/fix-DCO.md)) - could you add that?

Hi @krisfreedain - sorry for the delay on this. I pushed some changes - does that address the concerns?

**Comment by krisfreedain** [comment]
> > Hello @haroonchoudery - so glad to see this PR! The repo requires a DCO sign off ([a few tips on retroactively applying a sign off](https://github.com/src-d/guide/blob/9171d013c648236c39faabcad8598be3c0cf8f56/developer-community/fix-DCO.md)) - could you add that?
> 
> Hi @krisfreedain - sorry for the delay on this. I pushed some changes - does that address the concerns?

Hello @haroonchoudery - looks like it's still not recognizing DCO sign off on this. 
@AMoo-Miki @dtaivpp @CEHENKLE - would you have input on how @haroonchoudery can go back and re-sign this so we can get it through DCO checks? thanks

**Comment by dtaivpp** [comment]
@haroonchoudery id recommend a rebase and force push since you have two commits without sign off now. 

```bash
git rebase --signoff HEAD^^
git push -f origin <branch name>
```

**Comment by haroonchoudery** [comment]
> ```shell
> git push -f origin <branch name>
> ```

sorry for the delay on this @krisfreedain @dtaivpp - hope this addresses the issues! 

I'm not super technically savvy 😄 so if there are still any issues, I'll get our eng team involved. thanks!

**Comment by krisfreedain** [comment]
Hello @haroonchoudery - I'll work on a resolution to this and get Highlight added to the partner page. Will update here as soon as resolved

**Comment by krisfreedain** [comment]
Hello @haroonchoudery - I've resolved the issues with DCO in https://github.com/opensearch-project/project-website/pull/1116 -- welcome to the [partners page](https://opensearch.org/partners)! Will close this one out.

**Pull request closed without merging**
