### PR TITLE
Added personal author file

### PR DESCRIPTION
**Pull request by sebastianingino**
Signed-off-by: Sebastian Ingino <sebasing@icloud.com>

### Description
Adds the personal author file for myself
 
### Issues Resolved
None

### Check List
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by joshuarrrr — CHANGES_REQUESTED** [review]
Please move the new file to the `_authors/osci_2023` directory. Otherwise looks good.

Who are your top jazz piano heroes? For me, it's McCoy Tyner, then Horace Silver.

**Comment by joshuarrrr** [comment]
Also, make sure all commits are signed by following the instructions in https://github.com/opensearch-project/project-website/pull/2144/checks?check_run_id=17027539111

**Comment by dtaivpp** [comment]
Hey can you fix your commits with the following?

1. In your local branch, run: `git rebase HEAD~2 --signoff`
2. Force push your changes to overwrite the branch: `git push --force-with-lease origin feat/profile`

**Comment by sebastianingino** [comment]
Fixed both issues, thank you! My top jazz pianists would probably be Bill Evans and John Lewis, but I'm also a huge fan of Gerald Clayton's recent work!

**Review by joshuarrrr — APPROVED** [review]
LGTM

**Review by dtaivpp — COMMENTED** [review]
Looks good!

**Review by dtaivpp — APPROVED** [review]

**Pull request merged**
