### PR TITLE
Adding OpenSearch checkup

### PR DESCRIPTION
**Pull request by shahar35**
The OpenSearch check-up analyzes architecture and configuration to provide you with specific recommendations for improvement and optimization. The Check-Up is free forever and based on JSON files so you don’t need to download or install anything.

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by stockholmux — CHANGES_REQUESTED** [review]
Content LGTM! However, it looks like you missed signing your commits and it's causing the DCO bot to fail :( 

[This guide shows how to quickly fix it](https://github.com/src-d/guide/blob/9171d013c648236c39faabcad8598be3c0cf8f56/developer-community/fix-DCO.md#fix-option-2-rebase-git213)

**Comment by shahar35** [comment]
Hey @stockholmux , 
Thanks for your review, I just performed Option #1 and  #2 on the link that you put on your comment with success. 

Adding OpenSearch checkup
 Author: Shahar <shahar@opster.com>
 Date: Wed Jan 26 16:10:21 2022 +0200
 1 file changed, 10 insertions(+)
 create mode 100644 _community_projects/opensearch-checkup.md
 
should I reopen the PR?

**Comment by stockholmux** [comment]
@shahar35 Did you re-push? I'm still seeing the original commit only.

**Comment by stockholmux** [comment]
Hooray @shahar35! It should be in production shortly!

**Pull request merged**
