### PR TITLE
Search links updates oct 6

### PR DESCRIPTION
**Pull request by astephanus**
### Description
Adds the Hybrid Search blog post to the search platform landing page, and the vector database page.
Updates a 3rd party integration link on the vector database page.

### Check List
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by krisfreedain — DISMISSED** [review]
LGTM - thanks @astephanus

**Comment by krisfreedain** [comment]
@astephanus - I got this message after I attempted to approve - may need to rebase? 

"The merge-base changed after approval."

**Comment by astephanus** [comment]
> @astephanus - I got this message after I attempted to approve - may need to rebase?
> 
> "The merge-base changed after approval."

Resolved

**Review by krisfreedain — APPROVED** [review]
thanks @astephanus

**Pull request merged**
