### PR TITLE
Update 2024 OpenSearch Project Public PGP Key Renewal Changelog

### PR DESCRIPTION
**Pull request by peterzhuamazon**
### Description
Update 2024 OpenSearch Project Public PGP Key Renewal Changelog
 
### Issues Resolved
https://github.com/opensearch-project/opensearch-build/issues/3468

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
We currently plan to get the key switched on 2024/05/07.

Thanks.

**Comment by peterzhuamazon** [comment]
cc: @krisfreedain @nateynateynate @bbarani 

Thanks!

**Review by nateynateynate — APPROVED** [review]
Looks good.

**Comment by peterzhuamazon** [comment]
Will go in as schedule on 2024/05/07.

**Comment by nateynateynate** [comment]
@peterzhuamazon - I for sure won't be around to do that. I'll be on a plane to Mexico tomorrow.

**Pull request merged**
