### PR TITLE
Add logstash oss with opensearch-output plugin:7.16.1 to download page

### LINKED ISSUE #581: Publish logstash-oss-with-opensearch-output 7.16.1 to download page
Is your feature request related to a problem? Please describe.
NA

Describe the solution you'd like
We would like to update logstash-oss-with-opensearch-output download link to latest version

Describe alternatives you've considered
N/A

Additional context
Relevant issue to release artifacts: opensearch-project/opensearch-build#1347

### PR DESCRIPTION
**Pull request by VijayanB**
### Description
Include new artifacts for 7.16.1 version
Update opensearch  to use logstash 7.16.1
 
### Issues Resolved
#581 

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by VijayanB** [comment]
This should be merged after artifacts are available

**Review by stockholmux — COMMENTED** [review]
does this also work with 1.0.0-1.1.1?

**Comment by VijayanB** [comment]
> does this also work with 1.0.0-1.1.1?

Updated. Can you review?

**Review by stockholmux — APPROVED** [review]
LGTM

**Pull request merged**
