### PR TITLE
[OSCI] Add new author

### PR DESCRIPTION
**Pull request by thanhinhchtom**
### Description
Add author
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by joshuarrrr — CHANGES_REQUESTED** [review]
Please remove the `<>` brackets from `name` and `github`. Otherwise, looks good.

**Comment by thanhinhchtom** [comment]
Should I remove it and create a new PR, or is it just a comment for the next time I make a PR?

**Comment by dtaivpp** [comment]
@thanhinhchtom if you commit it to the same branch it will just update this PR.

**Review by joshuarrrr — APPROVED** [review]
LGTM

**Review by dtaivpp — APPROVED** [review]
Looks great!

**Pull request merged**
