### PR TITLE
Adds Hostkey as a new partner

### PR DESCRIPTION
**Pull request by hkadm**
### Description
Adds Hostkey as a new partner
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by pajuric** [comment]
@hkadm - Thank you for filing to become a partner. If you have a moment, please go ahead and submit the following issue to establish a partner page, so our community knows who you are, how to work with you, and where to contact you. https://github.com/opensearch-project/project-website/issues/new?assignees=&labels=enhancement%2C+untriaged&projects=&template=partner_information.md&title=

**Comment by hkadm** [comment]
@pajuric Done.

**Review by nateynateynate — APPROVED** [review]
Works for me. Fair warning, we're going to be normalizing a lot of this partner metadata so that there's a finite number of choices to choose from.

**Comment by pajuric** [comment]
@hkadm - Is there a marketing or business contact I can reach out to? I do not have contact info for your organization.

**Pull request merged**
