### PR TITLE
Markdown blurb

### PR DESCRIPTION
**Pull request by RishabBha0428**
### Description
Added Rishab to authors directory
 
### Issues Resolved
None

### Check List
Signed-off-by: Rishab Bhatia [rishab_bhatia248@berkeley.edu]

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by cwperks — CHANGES_REQUESTED** [review]
Please move this to `_authors/osci_2023/` folder and remove extra newlines at the bottom of the file. 

Otherwise this LGTM.

**Comment by RishabBha0428** [comment]
> Please move this to `_authors/osci_2023/` folder and remove extra newlines at the bottom of the file.
> 
> Otherwise this LGTM.

Fixed the changes.

**Review by cwperks — APPROVED** [review]
LGTM!

**Comment by cwperks** [comment]
Please fix the DCO errors by signing commits

**Comment by RishabBha0428** [comment]
> Please fix the DCO errors by signing commits

Finished

**Comment by dtaivpp** [comment]
Closing as we are past deadline and there are outstanding changes.

**Pull request closed without merging**
