### PR TITLE
Fixes typo on Downloads page

### PR DESCRIPTION
**Pull request by tmarkley**
### Description

Before:
`3. Have a nice coffee while everything is downloading and startup up`

After:
`3. Have a nice coffee while everything is downloading and starting up`

Signed-off-by: Tommy Markley <markleyt@amazon.com>
 
### Issues Resolved
https://github.com/opensearch-project/project-website/issues/201

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by dblock — APPROVED** [review]

**Review by dblock — APPROVED** [review]
I think you're supposed to make this PR into staging (I always get confused too). Don't have permissions to merge in this repo either way :(

**Comment by dblock** [comment]
https://github.com/opensearch-project/project-website/issues/57

**Review by stockholmux — APPROVED** [review]
LGTM

**Comment by stockholmux** [comment]
Thanks @tmarkley! 

@dblock For something this small, I'll just merge it directly in. It's still a mess as far as how we go from `staging` to `main` (🤞  we can fix it now that 1.0 GA is behind us), but once we setup `main` as the editing branch we'll enforce not pushing things directly to production.

**Pull request merged**
