### PR TITLE
Update carousel arrows

### PR DESCRIPTION
**Pull request by astephanus**
### Description
Applies new hero carousel arrow icons from the design library with San Francisco Fog for the community voices carousel, and white for the homepage hero carousel.

### Check List
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by krisfreedain — APPROVED** [review]
LGTM - thanks @astephanus

**Review by krisfreedain — APPROVED** [review]

**Comment by krisfreedain** [comment]
another one @astephanus - can you look into this?

"The merge-base changed after approval."

**Comment by astephanus** [comment]
> another one @astephanus - can you look into this?
> 
> "The merge-base changed after approval."

This should be good to go.

**Review by krisfreedain — APPROVED** [review]
thanks @astephanus

**Pull request merged**
