### PR TITLE
[OSCI] Add new author Jinen Setpal

### PR DESCRIPTION
**Pull request by jinensetpal**
### Description
Added my user profile
 
### Issues Resolved
N/A

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by cwperks — CHANGES_REQUESTED** [review]
Hi @jinensetpal, please move this file into the [`authors/osci_2023`](https://github.com/opensearch-project/project-website/tree/main/_authors/osci_2023) folder.

Otherwise this LGTM!

**Comment by jinensetpal** [comment]
Hi @cwperks, thanks for the catch! Made the change.

**Review by joshuarrrr — APPROVED** [review]
LGTM

**Review by dtaivpp — APPROVED** [review]
LGTM!

**Pull request merged**
