### PR TITLE
Coralogix partner page

### PR DESCRIPTION
**Pull request by astephanus**
### Description
Extended partner page for Coralogix.
 
### Issues Resolved
https://github.com/opensearch-project/project-website/issues/1935#issuecomment-1696589576

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by krisfreedain** [comment]
@astephanus - got an odd error running locally:

"             Error: YAML Exception reading /OpenSearch/temp-astephanus-coralogix-partner-page-project-website/_exhibitors/coralogix.md: (<unknown>): found unexpected end of stream while scanning a quoted scalar at line 4 column 7"

**Comment by astephanus** [comment]
> @astephanus - got an odd error running locally:
> 
> " Error: YAML Exception reading /OpenSearch/temp-astephanus-coralogix-partner-page-project-website/_exhibitors/coralogix.md: (): found unexpected end of stream while scanning a quoted scalar at line 4 column 7"

Thanks @krisfreedain. I'm not entirely sure how that slipped through the cracks. Nevertheless, it is resolved.

**Review by nateynateynate — APPROVED** [review]
Welcome to Opensearch.org Coralogix!

**Review by krisfreedain — APPROVED** [review]
thanks @astephanus

**Review by krisfreedain — APPROVED** [review]

**Review by krisfreedain — APPROVED** [review]

**Review by nateynateynate — APPROVED** [review]
Looks good to me.

**Review by dtaivpp — DISMISSED** [review]
Looks good!

**Comment by astephanus** [comment]
Closing because of Github confusion about "merge-base change" message. Redone in PR https://github.com/opensearch-project/project-website/pull/1946

**Pull request closed without merging**
