### PR TITLE
Added DigitalPebble to partners

### PR DESCRIPTION
**Pull request by jnioche**
Signed-off-by: Julien Nioche <julien@digitalpebble.com>

### Description
Adds DigitalPebble to the list of partners
 
### Issues Resolved
Non

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

DigitalPebble Ltd created a [module for OpenSearch](https://github.com/DigitalPebble/storm-crawler/tree/master/external/opensearch) in StormCrawler. @macrakis suggested that we add ourselves to the list of partners

### CODE REVIEW

**Comment by krisfreedain** [comment]
Fantastic! thanks @jnioche (and thanks @macrakis) - one minor adjustment - can you ensure your logo is square? It throws off the lineup a bit if not. Example:
Screen Shot 2023-01-18 at 11 39 43 AM

**Comment by krisfreedain** [comment]
That is a great looking logo @jnioche - works well for the partner page. 

I wanted to ask, I see ES listed on both the digital pebble site as well as the storm crawler site, but don't see OpenSearch mentioned - is that coming soon?

**Comment by jnioche** [comment]
Hi @krisfreedain, thanks for the nudge ;-) I've updated both DigitalPebble and StormCrawler's pages so that they mention OpenSearch

**Comment by krisfreedain** [comment]
Fantastic! welcome to the partners page @jnioche - we're happy you're here.

**Comment by jnioche** [comment]
thanks @krisfreedain that's great!

**Pull request merged**
