### PR TITLE
Add Fess to Community Projects page

### PR DESCRIPTION
**Pull request by marevol**
### Description
Fess is an enterprise search server that supports OpenSearch as a search engine.
I'd like to add Fess to the Community Projects page.
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by stockholmux — APPROVED** [review]
Awesome! LGTM

**Comment by stockholmux** [comment]
@marevol Thanks so much for your contribution. 

I think our community would love to hear more about Fess. Would you like to present it at our community meeting?

**Comment by marevol** [comment]
Could you give me more information about the community meeting? I may do it if I have time to prepare it. (I'm busy these days...)

**Comment by stockholmux** [comment]
@marevol Yeah! We're always looking for 10-15 minute presentations. It would be a great way to introduce the community to Fess and what it does. We have some that are in the afternoons for the US (7am Tokyo time).

**Pull request merged**
