### PR TITLE
Added hossted as partner

### PR DESCRIPTION
**Pull request by liorkesos**
### Description
Adds hossted as a partner (after onboarding discussion with Kyle Davis 

### Issues Resolved
none

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by stockholmux — CHANGES_REQUESTED** [review]
Looks good, however two things:
1) The repo requires a DCO sign off ([a few tips on retroactively applying a sign off](https://github.com/src-d/guide/blob/9171d013c648236c39faabcad8598be3c0cf8f56/developer-community/fix-DCO.md)) - could you add that?
2) Do you have a square format of your logo? It looks a little off in context of the rest of the logos. If not, do you mind of we add some space above/below your logo for positions reasons
Screen Shot 2022-01-10 at 4 00 31 PM

**Comment by krisfreedain** [comment]
Hello @liorkesos - wanted to follow up on this one

**Comment by krisfreedain** [comment]
@liorkesos - wanted to follow up on this

**Comment by krisfreedain** [comment]
@pajuric - wondered if you'd heard anything back from them - let me know, if not, I guess we'll close this out.

**Comment by liorkesos** [comment]
Hi guys, sorry for bkt being responsive.
I'll try to submit an altered logo ...

**Comment by krisfreedain** [comment]
Hello @liorkesos - wanted to follow up on this.

**Comment by liorkesos** [comment]
Signed-off and trying to submit with the proper dimensions....

**Comment by liorkesos** [comment]
@krisfreedain - I tried to resubmit in the original PR - I hope i didn't make a mess...

**Comment by krisfreedain** [comment]
Hello @liorkesos - looks good. Appears there is still a DCO issue though. I'll go ahead and see if I can redo it on your behalf.

**Comment by krisfreedain** [comment]
hello @liorkesos - I've resolve the issues - welcome to the OpenSearch partner page! 
https://github.com/opensearch-project/project-website/pull/1254

**Pull request closed without merging**
