### PR TITLE
Add Elastisys to list of partners

### LINKED ISSUE #3052: Elastisys in partner page
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
Elastisys

**Brief description of your business and what it does (50 words or less)**
Elastisys, founded in 2011 and based in Sweden, specializes in cloud native technologies. We offer a cloud native Kubernetes platform, optimized for security and compliance with EU regulations for software critical to our society. Our solutions enable customers to accelerate innovation, reduce costs, and enhance security using our leading cloud native technology and expertise.

**Name of your relevant product(s) or service for the OpenSearch audience**
Elastisys has developed Compliant Kubernetes. Elastisys Compliant Kubernetes enables organizations across Europe to accelerate innovation through open source cloud-native technology, while ensuring security and regulatory compliance. Elastisys utilize Opensearch as part of our offering to provide our customers with out of the box logging for Kubernetes environments.

**What OpenSearch technologies do you specialize in**
Observability, Security, Search, Analytics

**Type of business**
Consultancy, Support, Product

**Home/main office location or address**
Kuratorvägen 2A, 907 36 Umeå, Sweden

**How can people contact you (email and phone)**
contact@elastisys.com, +46101471000

**Regions you serve**
Europe 

**Industry specialization**
Software and technology

**Logo**
Elastisys-logo_square_midnight

**Additional image**
Attach any additional image you would like to provide that showcase your business (product, technology, offices)

**Links**
- [Logs in Elastisys Kubernetes Offering](https://elastisys.io/compliantkubernetes/user-guide/logs)
- [Elsa Science – Customer Success Story](https://elastisys.com/elsa-science-customer-success-story/)
- [Log based Alerts](https://elastisys.io/compliantkubernetes/user-guide/log-based-alerts/)

### PR DESCRIPTION
**Pull request by salehsedghpour**
### Description
This PR adds Elastisys to list of partners. Elastisys has developed Compliant Kubernetes. Elastisys Compliant Kubernetes enables organizations across Europe to accelerate innovation through open source cloud-native technology, while ensuring security and regulatory compliance. Elastisys utilize Opensearch as part of the offering to provide our customers with out of the box logging for Kubernetes environments.
 
### Issues Resolved
Fixes #3052 

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by pajuric** [comment]
@salehsedghpour - Thank you for submitting to become partner. Please submit this issue to setup your own personalized partner page: https://github.com/opensearch-project/project-website/issues/new?assignees=&labels=enhancement%2C+untriaged&projects=&template=partner_information.md&title= 

Also, please reach out to me at pattijur@amazon.com, as I am the partner manager and would like to schedule time for us to discuss partnership and help onboard you to the project.

**Comment by salehsedghpour** [comment]
Thank you @pajuric! I just created the issue #3015.

**Review by nateynateynate — APPROVED** [review]
Thanks for joining us, Elastisys!

**Review by krisfreedain — APPROVED** [review]
Looks good - thanks @salehsedghpour 

@pajuric - here we go!

**Pull request merged**
