### PR TITLE
Release Data Prepper 2.6.0

### PR DESCRIPTION
**Pull request by asifsmohammed**
### Description
Adds Data Prepper 2.6.0 and updates links to Data Prepper 2.6.0
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by dlvenable — APPROVED** [review]

**Comment by dlvenable** [comment]
We are releasing in the afternoon on Tuesday, Nov 28.

**Comment by dlvenable** [comment]
For #2416

**Comment by dlvenable** [comment]
This is released and we can merge this at any point now.

**Review by krisfreedain — APPROVED** [review]
Looks good!

**Pull request merged**
