### PR TITLE
WorldTech IT Partner Link

### PR DESCRIPTION
**Pull request by ericwtit**
### Description
Adds Partner link for WorldTech IT
 
### Issues Resolved
n/a

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by nateynateynate — APPROVED** [review]
Jekylll front matter and logo - looks okay to me.

**Comment by ericwtit** [comment]
Hey team, went through and tried to add the DCO to every commit and included the draft blog post plus its assets. I'll repeat the blog post template below as well. Let me know if there's anything to correct—thanks for your help!

**Describe the blog post your would like to write**
Explaining how WorldTech IT as a Partner is using OpenSearch to observe and manage F5 and NGINX.

**What is the title of the blog post?**
Partner Highlight: Using OpenSearch for F5 & NGINX with WorldTech IT

**Who are the authors?**
- Austin Geraci
- Ryan Paras

**What is the proposed posting date?**
Monday, June 6, 2022 (obviously this can be moved back if necessary!)

**Comment by krisfreedain** [comment]
Hello @ericwtit - looks like DCO is still failing. Can you make the necessary changes to your submit?
https://github.com/opensearch-project/project-website/pull/850/checks?check_run_id=6730999867

**Comment by ericwtit** [comment]
> 
Hey @krisfreedain I think we're in the clear? Let me know if there's anything else I can do on my end—thanks!

**Review by krisfreedain — APPROVED** [review]
Looks great - thanks for fixing the DCO @ericwtit

**Pull request merged**
