### PR TITLE
Request for Smart Search Tools and Weblink Technology as partners

### PR DESCRIPTION
**Pull request by sribalajivelan-weblinktechs**
### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by krisfreedain** [comment]
Hello @sribalajivelan-weblinktechs - welcome! Glad to get this PR.  A couple minor things to work through
- can you make sure the logos are uploaded as square images? it tends to throw off the alignment of the current partner page if they aren't: 
Screen Shot 2023-02-27 at 9 32 34 AM
- I didn't see OpenSearch mentioned on weblinktechs.com - wondered if you are working to add that
- DCO is a requirement but seems to have failed - can you make sure to sign when you edit the images? That will allow me to quickly move this forward

thank you!

**Comment by sribalajivelan-weblinktechs** [comment]
@krisfreedain I updated the logo and DCO, we will update the site to mention open search, please verify and approve the request, if any other change need to let me know

**Review by krisfreedain — APPROVED** [review]
thanks @sribalajivelan-weblinktechs - looking forward to seeing OpenSearch mentioned on the site - pushing this through

**Comment by dblock** [comment]
The https://weblinktechs.com website seems down now, @sribalajivelan-weblinktechs? Thanks.

**Pull request merged**
