### PR TITLE
Add Partner Tornis in OpenSearch

### PR DESCRIPTION
**Pull request by tornis**
### Description
Add Partner Tornis Tecnologia in OpenSearch

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by tornis** [comment]
Adjusting pending issues suggested by Opensearhc time.

**Comment by tornis** [comment]
Signature adjustment requested by DCO

**Review by krisfreedain — CHANGES_REQUESTED** [review]
Hello @tornis - files look great and we're happy to add you as a partner - one small change needed - please complete the DCO signoff so I can merge this request. thanks

**Comment by tornis** [comment]
> Hello @tornis - files look great and we're happy to add you as a partner - one small change needed - please complete the DCO signoff so I can merge this request. thanks

**Pull request closed without merging**
