### PR TITLE
[OSCI] Add New Author johnhurst

### PR DESCRIPTION
**Pull request by hurstjohn**
### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by dtaivpp — CHANGES_REQUESTED** [review]
Hey, there is no information in here! Can you please fill in and  can you move your bio from the `_authors` to the `_authors/osci_2023` directory.

**Comment by hurstjohn** [comment]
> Hey, there is no information in here! Can you please fill in and can you move your bio from the `_authors` to the `_authors/osci_2023` directory.

Sorry, I didn't realize there was a template. I just copied the contents. I just committed the changes now. Thanks

**Review by dtaivpp — COMMENTED** [review]
Approved!

**Review by dtaivpp — APPROVED** [review]
Looks good!

**Review by dtaivpp — APPROVED** [review]
Looks good!

**Pull request merged**
