### PR TITLE
[OSCI] Add new osci author kenny zhang

### PR DESCRIPTION
**Pull request by kennyzhang0819**
### Description
I added new osci author kenny zhang (myself)
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by ashwin-pc — CHANGES_REQUESTED** [review]
@kennyzhang0819 can you move the file to `_authors/osci_2023`? Sorry there was a mistake in my instructions. Apologies for that.

**Comment by dtaivpp** [comment]
@kennyzhang0819 you are missing the signoff on that latest commit. Can you run this to resolve: 
1. In your local branch, run: `git rebase HEAD~3 --signoff`
2. Force push your changes to overwrite the branch: `git push --force-with-lease origin chore/kenny-pc`

**Comment by kennyzhang0819** [comment]
Hi, can you check again and see if this is correct?

**Review by joshuarrrr — APPROVED** [review]
LGTM

**Review by dtaivpp — APPROVED** [review]
Looks great!~

**Pull request merged**
