### PR TITLE
Newpartnerlogit

### PR DESCRIPTION
**Pull request by Ebennetteng**
### Description
[Adding Logit.io to partners page]

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by krisfreedain** [comment]
Hello @Ebennetteng - glad to see this PR! The repo requires a DCO sign off ([a few tips on retroactively applying a sign off](https://github.com/src-d/guide/blob/9171d013c648236c39faabcad8598be3c0cf8f56/developer-community/fix-DCO.md)) - could you add that?

**Comment by Ebennetteng** [comment]
> 

Just used git commit --amend --no-edit --signoff now, fingers crossed that worked

**Comment by krisfreedain** [comment]
@Ebennetteng unfortunately, it looks like it did not work  https://github.com/opensearch-project/project-website/pull/959/checks?check_run_id=7994914526

**Comment by krisfreedain** [comment]
hello @Ebennetteng - I'll work on a resolution to this and get you added to the partner page. Will update here as soon as resolved

**Comment by krisfreedain** [comment]
Hello @Ebennetteng - I've resolved the issues with DCO in https://github.com/opensearch-project/project-website/pull/1116 -- welcome to the [partners page](https://opensearch.org/partners)! Will close this one out.

**Pull request closed without merging**
