### PR TITLE
Add Malcolm (https://github.com/idaholab/malcolm) to the list of Community projects

### PR DESCRIPTION
**Pull request by mmguero**
Add Malcolm (https://github.com/idaholab/malcolm) to the list of Community projects.

### Description

Malcolm recently switched from Elastic to OpenSearch and OpenSearch dashboards (see
idaholab/Malcolm#54) and would be proud to be listed among the community projects
using OpenSearch.

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by elfisher** [comment]
Taking a look.

**Comment by elfisher** [comment]
@mmguero, this LGTM! Thanks for sharing and submitting this PR. Before I approve, I wanted to double check that what I see in my local website build is inline with what you expect. Thanks!

image

**Comment by mmguero** [comment]
> @mmguero, this LGTM! Thanks for sharing and submitting this PR. Before I approve, I wanted to double check that what I see in my local website build is inline with what you expect. Thanks!

Yeah, I think that looks fine!

**Review by elfisher — APPROVED** [review]
Approved.

**Review by stockholmux — APPROVED** [review]
LGTM

**Pull request merged**
