### PR TITLE
Create addweb.md

### PR DESCRIPTION
**Pull request by ashishaddweb**
added addwebsolution details please approve

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by ashishaddweb** [comment]
Hey @nknize @AMoo-Miki @krisfreedain @all 
Please take a moment to review my request and consider merging it. I am truly excited about the opportunity to join this community. Thank you.

**Review by nateynateynate — CHANGES_REQUESTED** [review]
It looks like you still have a lot of placeholder images where your product and logo images should be. Do you mind uploading the appropriate images?

**Comment by ashishaddweb** [comment]
Thanks [dtaivpp](https://github.com/dtaivpp) for bringing this to my attention! I'm sorry for the oversight, and I appreciate your input.

I'll definitely add a section about our search solutions with OpenSearch on the website. Once it's done, i will update you for further process.

Your feedback means a lot to us, so please don't hesitate to share more suggestions. Thanks again!

**Comment by nateynateynate** [comment]
Feel free to reopen this if necessary. I'm going to close it out for now as a matter of housekeeping.

**Pull request closed without merging**
