### PR TITLE
Adds new author KakaInnocent

### PR DESCRIPTION
**Pull request by KakaInnocent**
### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by KakaInnocent** [comment]
Sorry for the delay

**Review by dtaivpp — CHANGES_REQUESTED** [review]
Hey, please move this file to `_authors/osci_2023/` and then we should be good to complete!

**Comment by KakaInnocent** [comment]
> Hey, please move this file to `_authors/osci_2023/` and then we should be good to complete!

Hey already done it maybe now we can check and proceed. Thank you

**Review by dtaivpp — APPROVED** [review]
Looks great!

**Pull request merged**
