### PR TITLE
Add Adelean partner info

### PR DESCRIPTION
**Pull request by bootis**
### Description
Added information about Adelean, search consulting company in France, as an OpenSearch partner.
 
### Issues Resolved
--

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by pajuric** [comment]
@bootis  - We look forward to partnering. Please also consider filing [GitHub issue #1345](https://github.com/opensearch-project/project-website/issues/1345) and proving the requested info to establish a custom partner page.

**Comment by bootis** [comment]
Thanks @pajuric. all the answers are actually what I wrote on the PR directly (adelean.md and new image files) -- Do you want me to create a new issue with the details and link it here?

**Review by dtaivpp — APPROVED** [review]
Looks good to me!

**Comment by pajuric** [comment]
> Thanks @pajuric. all the answers are actually what I wrote on the PR directly (adelean.md and new image files) -- Do you want me to create a new issue with the details and link it here?

@bootis Yes please. The issue for the partner page is separate from this and requires additional info in order to create that additional page on our site, and add you to the partner selector guide we are building.

**Pull request merged**
