### PR TITLE
Adds new community project

### PR DESCRIPTION
**Pull request by toluaina**
Signed-off-by: toluaina <toluaina@hotmail.com>

### Description
- add PGSync as a new community project
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by toluaina** [comment]
> Hi,
> 
> I checked the resources but I did not understand how it was relevant to OpenSearch. Do you think you can clarify that?
> 
> Thank you. Lukáš

Hi,

PGSync is an open source tool that works with both Opensearch and Elasticsearch.
It is also listed as an Integration tool in the community supported tools over [there](https://www.elastic.co/guide/en/elasticsearch/plugins/8.5/integrations.html).
It is listed in the Postgres Software [catalogue](https://www.postgresql.org/download/products/1-administrationdevelopment-tools/) as an administration/development tools.

thanks,

**Comment by lukas-vlcek** [comment]
Hi Tolu,

I am not a PG person so I apology for my ignorance but when I was trying to find any information about OpenSearch support I was not much successful. There is no information about it on https://pgsync.com/ (even the full-text search yields zero results for "OpenSearch"), the repository https://github.com/toluaina/pgsync/ does not mention it as well – at least not in README file (though GH full-text search gave me some results mostly on issues). The Postgres Software catalogue does not mention OpenSearch as well. So as an OpenSearch person I am struggling to find any relevant information – for example about OpenSearch versioning support (is there any CI integration with OpenSearch?).

It sounds to me that there is an assumption that if it supports Elasticsearch then it supports OpenSearch as well and both product terms can be used almost interchangeably. Although this could be true on the technical level to some degree it is IMO questionable approach from the legal perspective.

Regards,
Lukáš

**Comment by dtaivpp** [comment]
I agree with Lukáš here. Its not apparent from PGSync's repo that it supports OpenSearch at all. I'd like to see a compatibility matrix showing versions of OpenSearch it's been tested with. While it may work natively with OpenSearch 1.3.x because of the API similarities with Elasticsearch it's likely going to need updates for the 2.x line.

**Comment by toluaina** [comment]
> I agree with Lukáš here. Its not apparent from PGSync's repo that it supports OpenSearch at all. I'd like to see a compatibility matrix showing versions of OpenSearch it's been tested with. While it may work natively with OpenSearch 1.3.x because of the API similarities with Elasticsearch it's likely going to need updates for the 2.x line.

Thanks for the constructive feedback.
I have updated the project documentation to include references to Opensearch specifically. 
I have also updated the PR to refer to Opensearch instead.
PGSync is fully compatible with Opensearch.
As the project maintainer, I use both Opensearch and Elasticsearch for development.

PGSync is compatible in areas where these two overlap. This is evident in the codebase.
Similarly, with Postgres, PGSync aims to ensure full compatibility with a 
minimum version requirement.

**Comment by toluaina** [comment]
Hello, 

In support of this, I have added a [docker-compose.yml ](https://github.com/toluaina/pgsync/blob/main/docker-compose-opensearch.yml)
for opensearch that works out of the box in the PGSync repo.

You can run it by cloning the repo and then run:

`docker-compose -f docker-compose-opensearch.yml up`

This should bring up all the services including the latest Opensearch
service.

thanks,

**Comment by krisfreedain** [comment]
thanks for the feedback @lukas-vlcek @dtaivpp 
thanks for this @toluaina - looks great - and I see the homepage now mentions OpenSearch. 

Can you name the file pgsync.md - check it in under the project-website/_community_projects/ folder - using DCO? Once that's done should be good to go.

**Review by lukas-vlcek — CHANGES_REQUESTED** [review]
Hi, just a small nit: please be aware of [proper trademark use](https://opensearch.org/trademark-usage.html). It should be OpenSearch (w/ capital "S").

**Comment by toluaina** [comment]
Thanks for looking at this. 
I have renamed Opensearch to OpenSearch. 
I have also changed all the references in the project documentation to camel case as well.
thanks,

--Tolu

**Comment by toluaina** [comment]
Hi 
I just realized you were waiting for action on my part for this PR. 
I have ticked the checklist according to the sign-off requirements.

thanks

--Tolu

**Review by krisfreedain — APPROVED** [review]
thanks @toluaina - welcome to the community project page!

**Pull request merged**
