### PR TITLE
Added Data Prepper 1.5.1 archives and updated version to 1.5.1

### PR DESCRIPTION
**Pull request by asifsmohammed**
Signed-off-by: Asif Sohail Mohammed <nsifmoh@amazon.com>

### Description
Added Data Prepper 1.5.1 linux archives, Dockerfile image and updated version to 1.5.1
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by dlvenable — APPROVED** [review]
Thanks Asif!

**Comment by dlvenable** [comment]
We are planning to release Data Prepper 1.5.1 today. We'd like this merged after the binaries are completed.

**Comment by dlvenable** [comment]
The Data Prepper binaries are now released and this can be merged at any time.

**Review by krisfreedain — APPROVED** [review]
looks good

**Pull request merged**
