### PR TITLE
adds more testimonials

### PR DESCRIPTION
**Pull request by elfisher**
### Description
Adds additional testimonials to the testimonial page.

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by elfisher** [comment]
@stockholmux some of the logos aren't rendering to similar sizes. let me know if you have suggestions on how we can fix that.

**Review by stockholmux — CHANGES_REQUESTED** [review]
It looks good, however the images need a little work.
- wipro is _huge_ at 188kb and 2560x2560. That's 10x file size of Goldman and double the resolution. It should be resized - really no need for the file to be that high res. On screen it's taking up 54 px square. We should over size these images to account for retina displays, but not 47x!
- wipro has a ton of padding built into the image which makes it look small when scaled - when I overlay goldman and wipro, you can see the difference. overlay. 
If you crop the wipro logo closer, they will appear closer in size

**Comment by elfisher** [comment]
> It looks good, however the images need a little work.
> 
> * wipro is _huge_ at 188kb and 2560x2560. That's 10x file size of Goldman and double the resolution. It should be resized - really no need for the file to be that high res. On screen it's taking up 54 px square. We should over size these images to account for retina displays, but not 47x!
> * wipro has a ton of padding built into the image which makes it look small when scaled - when I overlay goldman and wipro, you can see the difference. 
>   If you crop the wipro logo closer, they will appear closer in size

Fixed accordingly. Looks better!

**Review by stockholmux — APPROVED** [review]
LGTM

**Pull request merged**
