### PR TITLE
Brian Park profile page created

### PR DESCRIPTION
**Pull request by brian-jw-park**
### Description
Adds Brian Park profile page
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by ashwin-pc — CHANGES_REQUESTED** [review]
can you move this to the `_authors/osci_2023` folder. My instructions in the gist were incorrect so apologies for that.

**Comment by brian-jw-park** [comment]
> can you move this to the `_authors/osci_2023` folder. My instructions in the gist were incorrect so apologies for that.

Hi Ashwin! I just had a quick question–to solve this, I was thinking of just repeating the entire process we covered on Day 2 and then creating my new file under _authors/osci_2023. I was wondering whether there was a simpler command to do this? I feel like git move could work but I was having trouble getting it to work successfully. Thank you!

**Comment by dtaivpp** [comment]
So typically the move command on most systems is `mv start_file_dest end_file_dest`

**Comment by dtaivpp** [comment]
Closing as requested changes were not made and we are past deadlines

**Pull request closed without merging**
