### PR TITLE
Add index compression benchmarking dashboard

### PR DESCRIPTION
**Pull request by bbarani**
### Description
Add index compression benchmarking dashboards to opensearch.org/benchmarks webpage
 
### Issues Resolved
NA

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by krisfreedain** [comment]
@bbarani - I wonder if the iframe needs to be / can be expanded at the bottom - the page cuts off the "2.9.0-SNAPSHOT: OpenSearch Version" area and won't display it very well

Screen Shot 2023-07-17 at 2 18 31 PM

**Comment by wbeckler** [comment]
@krisfreedain can you check on a narrower screen? Also, the same issue might exist on today's report. If it's not a net new problem, can you sign off? @bbarani can you take a look otherwise?

**Comment by bbarani** [comment]
@krisfreedain I don't see this issue on my local. I have added table with the data now below the graph but I don't see it chopped off in full page view (on desktop).

Screen Shot 2023-07-19 at 12 29 04 PM

**Comment by bbarani** [comment]
@krisfreedain I just realized that you are looking in to the wrong menu header. This PR is to add new menu for index compression and the issue you pointed out is for different header.

**Comment by bbarani** [comment]
@krisfreedain @AMoo-Miki Can you please review this PR again? CC: @wbeckler @CEHENKLE

**Review by krisfreedain — APPROVED** [review]
LGTM

**Pull request merged**
