### PR TITLE
[OSCI] Added Author Profile Picture

### PR DESCRIPTION
**Pull request by vvavdiya**
### Description
[OSCI] Added Author Profile Picture
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by vvavdiya** [comment]
@nateynateynate 
removed dashes from frontmatter elements

**Review by ashwin-pc — CHANGES_REQUESTED** [review]
Hey @vvavdiya can you move this file to `_authors/osci_2023/`

**Comment by vvavdiya** [comment]
@ashwin-pc 
Moved author profile file into `_author/osci_2023/`

Thanks

**Comment by vvavdiya** [comment]
> Let's take the dashes out of the frontmatter elements. We still need the triple dash at the start and end of the frontmatter, but each frontmatter element doesn't need a dash.

@nateynateynate 
Removed the dashes.

@nateynateynate @ashwin-pc 
Request to Merge the PR incase it's okay

**Review by ashwin-pc — APPROVED** [review]
LGTM!

**Review by nateynateynate — APPROVED** [review]
Looks good to me! thanks Vijay!

**Pull request merged**
