### PR TITLE
Adds artifact links for logstash-oss-with-opensearch-output-plugin-8.6.1

### PR DESCRIPTION
**Pull request by sshivanii**
### Description
Adds artifact links in [Downloads](https://opensearch.org/downloads.html) page for logstash-oss-with-opensearch-output-plugin-8.6.1
 
### Issues Resolved
N/A

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by dlvenable — CHANGES_REQUESTED** [review]
@sshivanii , You will also need to update all the OpenSearch versions to point their downloads to this version.

All the files in here: https://github.com/opensearch-project/project-website/tree/main/_versions

Here is one example. You can see it is using 8.4.0.

https://github.com/opensearch-project/project-website/blob/bcf4974656bcbf44258d3cb89c72551e827703a9/_versions/2023-01-24-opensearch-2.5.0.markdown?plain=1#L18-L19

You can probably find-and-replace `version: 8.4.0` with `version: 8.6.1`

**Comment by sshivanii** [comment]
> @sshivanii , You will also need to update all the OpenSearch versions to point their downloads to this version.
> 
> All the files in here: https://github.com/opensearch-project/project-website/tree/main/_versions
> 
> Here is one example. You can see it is using 8.4.0.
> 
> https://github.com/opensearch-project/project-website/blob/bcf4974656bcbf44258d3cb89c72551e827703a9/_versions/2023-01-24-opensearch-2.5.0.markdown?plain=1#L18-L19
> 
> You can probably find-and-replace `version: 8.4.0` with `version: 8.6.1`

Thanks for pointing this out. Since it's around 20+ files do we want to include them in this PR?

**Comment by dlvenable** [comment]
> Thanks for pointing this out. Since it's around 20+ files do we want to include them in this PR?

Yes, they should all be modified. 

This is a mapping of "best working" versions for each OpenSearch service. Since the 8.6.1 version is the best for OpenSearch 1.0-2.5.x, all of them need to be updated.

**Review by dlvenable — APPROVED** [review]
Thank you @sshivanii !

**Pull request merged**
