### PR TITLE
Adds new partner

### PR DESCRIPTION
**Pull request by oriserra**
Signed-off-by: oriserra <o.serra@sease.io>

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by oriserra** [comment]
Signed-off-by: oriserra <o.serra@sease.io>

**Comment by dtaivpp** [comment]
Hey @oriserra the DCO is failing here because you committed with your obfuscated github email but signed with your actual. Would you mind fixing this so we can review?

**Comment by oriserra** [comment]
> Hey @oriserra the DCO is failing here because you committed with your obfuscated github email but signed with your actual. Would you mind fixing this so we can review?

**Comment by dtaivpp** [comment]
Sure thing! Right now your GitHub global username/email is set as 'oriserra <111053790+oriserra@users.noreply.github.com>' 

but your signature came through as 'Signed-off-by: oriserra <o.serra@sease.io>'

To remedy you will either need to set up your global user email with: `git config --global user.email o.serra@sease.io` or modify the way you sign to use the anonymized email.

**Comment by oriserra** [comment]
> Sure thing @oriserra! Right now your GitHub global username/email is set as 'oriserra [111053790+oriserra@users.noreply.github.com](mailto:111053790+oriserra@users.noreply.github.com)'
> 
> but your signature came through as 'Signed-off-by: oriserra [o.serra@sease.io](mailto:o.serra@sease.io)'
> 
> To remedy you will either need to set up your global user email with: `git config --global user.email o.serra@sease.io` or modify the way you sign to use the anonymized email.

Hello, it should be done now. Cheers.

**Comment by dtaivpp** [comment]
Hey @oriserra that commit came through the same way as the last actually. Here are ([a few tips on retroactively applying a sign off](https://github.com/src-d/guide/blob/9171d013c648236c39faabcad8598be3c0cf8f56/developer-community/fix-DCO.md). 

Additionally, would you mind including your logo in the assets path mentioned on the template? Right now it is just linked. We like to build them in as the site is statically generated to improve performance.

**Comment by oriserra** [comment]
> Hey @oriserra that commit came through the same way as the last actually. Here are ([a few tips on retroactively applying a sign off](https://github.com/src-d/guide/blob/9171d013c648236c39faabcad8598be3c0cf8f56/developer-community/fix-DCO.md).
> 
> Additionally, would you mind including your logo in the assets path mentioned on the template? Right now it is just linked. We like to build them in as the site is statically generated to improve performance.

Thank you @dtaivpp, I found the configuration on Github so I am going to open a new pull request.

**Pull request closed without merging**
