### PR TITLE
Adds Link checker and fixes links

### LINKED ISSUE #206: Add an automated link checker
Coming from #205

### PR DESCRIPTION
**Pull request by ashwin-pc**
### Description

1. Adds a Link checker plugin to the project website.
2. Fixes broken internal links in the project website 

----

_Update_
1. Fixes broken external links
2. Adds Retry for HTTP Code: 429 responses

### Notes:
To run the link checker, add the ENV flag `JEKYLL_LINK_CHECKER` or `JEKYLL_FATAL_LINK_CHECKER` with any one of the valid values internal,forced,external,retry. Each option tests a larger range of links. The link checker does not run by default. This was done to ensure that the rebuild during development did not take too long.

#### `JEKYLL_LINK_CHECKER` vs `JEKYLL_FATAL_LINK_CHECKER`
They both accept the same values with the only difference being that `JEKYLL_FATAL_LINK_CHECKER` fails the build if a broken link is found

#### Env values
1. internal: validates only the internal links
2. forced: validates internal links and links that are technically internal but instead link to an external page. e.g. /docs
3. external: validates all links. however this option does not retry or follow links. e.g. HTTP:429 (too many attrmpts, retry after), HTTP:301 (Permanent redirect)
4. retry: validates all the links but also retries links with retry-able http header
 
### Issues Resolved
#206 

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by stockholmux** [comment]
So, I did test this out on my other machine, but I'm using a temp machine with an older version of Ruby and it seems to be throwing an error message:

```
/.gem/ruby/2.4.5/gems/jekyll-4.2.0/lib/jekyll/external.rb:60:in `require': /repos/ashwin-project-website/_plugins/link-checker.rb:95: syntax error, unexpected ']' (SyntaxError)
+[^>]+(?:id|name)="#{href[1..]}"/i).nil?
                              ^
/repos/ashwin-project-website/_plugins/link-checker.rb:96: syntax error, unexpected tCONSTANT, expecting tSTRING_DEND
        @failures << "Process:: ##{href[1..]}, linked in ./
                             ^
/repos/ashwin-project-website/_plugins/link-checker.rb:100: syntax error, unexpected keyword_end, expecting tSTRING_DEND
      end
         ^
/repos/ashwin-project-website/_plugins/link-checker.rb:229: syntax error, unexpected keyword_end, expecting tSTRING_DEND
/repos/ashwin-project-website/_plugins/link-checker.rb:253: syntax error, unexpected end-of-input, expecting tSTRING_DEND
	from /.gem/ruby/2.4.5/gems/jekyll-4.2.0/lib/jekyll/external.rb:60:in `block in require_with_graceful_fail'
	from /.gem/ruby/2.4.5/gems/jekyll-4.2.0/lib/jekyll/external.rb:57:in `each'
	from /.gem/ruby/2.4.5/gems/jekyll-4.2.0/lib/jekyll/external.rb:57:in `require_with_graceful_fail'
	from /.gem/ruby/2.4.5/gems/jekyll-4.2.0/lib/jekyll/plugin_manager.rb:89:in `block in require_plugin_files'
	from /.gem/ruby/2.4.5/gems/jekyll-4.2.0/lib/jekyll/plugin_manager.rb:87:in `each'
	from /.gem/ruby/2.4.5/gems/jekyll-4.2.0/lib/jekyll/plugin_manager.rb:87:in `require_plugin_files'
	from /.gem/ruby/2.4.5/gems/jekyll-4.2.0/lib/jekyll/plugin_manager.rb:21:in `conscientious_require'
	from /.gem/ruby/2.4.5/gems/jekyll-4.2.0/lib/jekyll/site.rb:131:in `setup'
	from /.gem/ruby/2.4.5/gems/jekyll-4.2.0/lib/jekyll/site.rb:36:in `initialize'
	from /.gem/ruby/2.4.5/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:30:in `new'
	from /.gem/ruby/2.4.5/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:30:in `process'
	from /.gem/ruby/2.4.5/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /.gem/ruby/2.4.5/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `each'
	from /.gem/ruby/2.4.5/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /.gem/ruby/2.4.5/gems/jekyll-4.2.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	from /.gem/ruby/2.4.5/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /.gem/ruby/2.4.5/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /.gem/ruby/2.4.5/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /.gem/ruby/2.4.5/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /.gem/ruby/2.4.5/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /.gem/ruby/2.4.5/gems/jekyll-4.2.0/exe/jekyll:15:in `<top (required)>'
	from /.gem/ruby/2.4.5/bin/jekyll:23:in `load'
	from /.gem/ruby/2.4.5/bin/jekyll:23:in `<top (required)>'
	from /.rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:63:in `load'
	from /.rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:63:in `kernel_load'
	from /.rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'
	from /.rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:481:in `exec'
	from /.rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /.rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /.rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /.rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:31:in `dispatch'
	from /.rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /.rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:25:in `start'
	from /.rubies/ruby-2.4.5/lib/ruby/gems/2.4.0/gems/bundler-2.2.25/exe/bundle:49:in `block in <top (required)>'
	from /.rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	from /.rubies/ruby-2.4.5/lib/ruby/gems/2.4.0/gems/bundler-2.2.25/exe/bundle:37:in `<top (required)>'
	from /.gem/ruby/2.4.5/bin/bundle:23:in `load'
	from /.gem/ruby/2.4.5/bin/bundle:23:in `<main>'
```

Is there something required as far as version of Ruby for this?

**Comment by ashwin-pc** [comment]
Interesting, the version i have on my system is `ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]`. This code is almost identical to the link checker on the [documentation website](https://github.com/opensearch-project/documentation-website/blob/main/_plugins/link-checker.rb)

**Comment by ashwin-pc** [comment]
Ive updated the PR to fix both internal and external links and rebased the commit to be on top of the latest changes in main.

**Comment by stockholmux** [comment]
@ashwin-pc OK. Looks like Jekyll requires ruby 2.5, so that's the source of the error I was getting on the other machine.

Can we add something to the README file with your info on `JEKYLL_LINK_CHECKER`, etc. info? I don't want that information to only exist in this PR.

Otherwise, I've checked everything and I'll merge after you add that bit in the readme.

**Comment by ashwin-pc** [comment]
Good point! I've added the instructions to the readme.

**Comment by stockholmux** [comment]
Thanks @ashwin-pc!

**Pull request merged**
