### PR TITLE
Create swirl.md

### PR DESCRIPTION
**Pull request by sid-swirl**
Initial commit

### Description
Add Swirl to OpenSearch partner
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by sid-swirl** [comment]
Signoff fixed, image added tnx

**Comment by sid-swirl** [comment]
Hi, just circling back on this. The mend workflow error seems to be because there are no assets matching the type of file that would trigger a scan? https://docs.mend.io/bundle/integrations/page/advanced_technical_information.html#Supported-Package-Manager-Dependency-Files

Anyway let me know, not sure what to do here

**Comment by dtaivpp** [comment]
Hey, I wanted to ask what the connection is between Swirl and OpenSearch? Are you backed by OpenSearch? I didn't see OpenSearch called out as a connector on your site. Just wanted to make sure I understand before pulling it in.

**Comment by sid-swirl** [comment]
@dtaivpp SWIRL fully supports OpenSearch. Here is an example SearchProvider: https://github.com/swirlai/swirl-search/blob/main/SearchProviders/opensearch.json

**Comment by nateynateynate** [comment]
Hi @sid-swirl ! Looks like this never got a follow up. Do you mind filling out [this issue template here](https://github.com/opensearch-project/project-website/issues/new?assignees=&labels=enhancement%2C+untriaged&projects=opensearch-project%2FWebsite+Update+Project&template=partner_add_new_partner.yml&title=%5BPARTNER%5D+%7B%7B+Company+name+%7D%7D+) to get a proper partner page created for you? Go ahead and mention this PR and we'll grab the logo out of it.

**Comment by nateynateynate** [comment]
Closing for housekeeping. If you'd still like to become an OpenSEarch partner, feel free to fill out the new github issue template to become one.

**Pull request closed without merging**
