### PR TITLE
Adding CrafterCMS as partner

### PR DESCRIPTION
**Pull request by russdanner**
### Description
Added markdown and logo for new partner: CrafterCMS, an open source, git-based headless CMS that is natively integrated with OpenSearch.
 
### Issues Resolved
Great content management for all :)

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by pajuric** [comment]
@russdanner - Great to have you as a new partner. While you're submitting to become a partner, you should also consider setting up your custom partner profile page by [filing an issue here](https://github.com/opensearch-project/project-website/issues/new?assignees=&labels=enhancement%2C+untriaged&projects=&template=partner_information.md&title=) with the requested info. I'd also like to schedule time to chat as the partner lead for OpenSearch - you can reach me at pattijur@amazon.com.

**Comment by dtaivpp** [comment]
Additionally would you mind uploading a square image?

**Comment by krisfreedain** [comment]
Hello @russdanner - I wanted to follow up on this one and see if you had time to take care of the two notes above. We'd love to get this one live and have you on the partner page. Thanks!

**Comment by pajuric** [comment]
@russdanner - Please let me know if I can help get your PR across the board. Thanks again. - PJ

**Comment by russdanner** [comment]
Hi All, 
I have updated the image to a square logo and signed off / fixed the commits with DCO 

Thanks [pattijur@amazon.com](mailto:pattijur@amazon.com). I will file the other listing request and reach out via email

**Comment by krisfreedain** [comment]
closing out with the merging of https://github.com/opensearch-project/project-website/pull/2394

**Pull request closed without merging**
