### PR TITLE
[OSCI] Added new OSCI author rlaracon

### PR DESCRIPTION
**Pull request by rlaracon**
### Description
Added new OSCI author rlaracon
 
### Issues Resolved
N/A

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by ashwin-pc — COMMENTED** [review]
@rlaracon can you move the file to `_authors/osci_2023`? Sorry i had an error in my notes.

**Comment by rlaracon** [comment]
> @rlaracon can you move the file to `_authors/osci_2023`? Sorry i had an error in my notes.

Moved it! Thank you.

**Review by joshuarrrr — APPROVED** [review]
LGTM

**Review by dtaivpp — APPROVED** [review]
Approved!

**Pull request merged**
