### PR TITLE
Adds new partner

### PR DESCRIPTION
**Pull request by m-kis**
Signed-off-by: m-kis <tech@m-kis.fr>

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by krisfreedain** [comment]
Hello @m-kis - welcome

Please be sure to submit a square logo with this PR, as well as a proper description. 
DCO is also a requirement
Lastly, is there anywhere on your site that talks about OpenSearch or related technologies? I could not find anything

thank you

**Comment by krisfreedain** [comment]
hello @m-kis - wanted to follow up on this with you

**Comment by krisfreedain** [comment]
never heard back from @m-kis

**Comment by m-kis** [comment]
Hello,

I don’t understand what do you want me to do, just mention OpenSearch on the website ?

Or something else. Sorry for the delay, I was not able to reply before.

Regards

[signature_1661647378]
[signature_1039909816]
[linkedin]
Cédric Merlin
CEO
M-KIS | Merlin Keep IT Simple

[mobilePhone]
+228 92 67 11 16 | +33 (0)6 64 18 27 46<tel:+33%20(0)6%2064%2018%2027%2046>
[emailAddress]
***@***.******@***.***>
[website]
https://m-kis.fr<https://m-kis.fr/>
[address]
4 rue cavé, 75018, Paris , France



De : Kris Freedain ***@***.***>
Date : jeudi, 30 mars 2023 à 01:46
À : opensearch-project/project-website ***@***.***>
Cc : m-kis ***@***.***>, Mention ***@***.***>
Objet : Re: [opensearch-project/project-website] Adds new partner (PR #1332)

never heard back from @m-kis<https://github.com/m-kis>

**Pull request closed without merging**
