### PR TITLE
[OSCI] Add new author Muhammad Samiullah

### PR DESCRIPTION
**Pull request by samipak458**
### Description
Adds my personal profile details.
 
### Issues Resolved
None

### Check List
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by Vinay-Vinod** [comment]
Looks good

**Review by dtaivpp — APPROVED** [review]
LGTM!

**Comment by kolchfa-aws** [comment]
Hey @samipak458 Could you remove the `@` in the twitter line? Also, I think this profile belongs in the _authors/osci_2023 folder. cc: @dtaivpp

**Comment by kolchfa-aws** [comment]
I've created the PR with the fix https://github.com/opensearch-project/project-website/pull/2268

**Comment by samipak458** [comment]
Sure, I will @kolchfa-aws.

**Comment by kolchfa-aws** [comment]
@samipak458 No worries, I created a PR already https://github.com/opensearch-project/project-website/pull/2268

**Pull request merged**
