### PR TITLE
Data Prepper 2.0.0 Downloads

### PR DESCRIPTION
**Pull request by oeyh**
Signed-off-by: Hai Yan <oeyh@amazon.com>

### Description

Prepares for Data Prepper 2.0 release:
- Adds Data Prepper 2.0.0 as a new artifact
- Updates all OpenSearch versions to use Data Prepper 2.0.0 as the version.

 
### Issues Resolved
N/A

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by dlvenable** [comment]
Data Prepper 2.0.0 is scheduled for release on Oct 10, 2022. We will notify in this issue when this PR is ready to merge.

**Comment by oeyh** [comment]
I have verified that the links are working properly after Data Prepper 2.0 artifacts are released.

**Comment by dlvenable** [comment]
We are ready to merge this PR. We have released the artifacts and @oeyh has verified they work here.

**Review by krisfreedain — APPROVED** [review]
Looks good

**Pull request merged**
