### PR TITLE
Adding Wazuh to community project list

### PR DESCRIPTION
**Pull request by snaow**
Hi team, sending the required data to add Wazuh to the community project list. 

### Description
Include Wazuh data and logo to the community project list.

### Issues Resolved
No issue required.

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by elfisher** [comment]
This LGTM

**Comment by elfisher** [comment]
@snaow would you be okay with using the same square logo used in the partner page for this PR too?

**Comment by snaow** [comment]
Yes! No problem with that. 
PR updated. 

Thanks again @elfisher

**Review by stockholmux — APPROVED** [review]
LGTM

**Comment by stockholmux** [comment]
Thanks @snaow!

**Pull request merged**
