### PR TITLE
Enhanced top nav

### PR DESCRIPTION
**Pull request by AMoo-Miki**
Signed-off-by: Miki <miki@amazon.com>

### Description
This is to introduce a 2-tier top navigation menu.

#### Wide Screen

https://user-images.githubusercontent.com/3527403/178615472-4587fd3a-fc75-46c3-accf-7241eb8b9279.mp4

#### Narrow Screen

narrow nav

### Check List
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by CEHENKLE** [comment]
I really like it Miki :) I also think the order across the top is very solid (first call to action being download, then about, then community, the documentation.

Can we also add "partner projects" under community?  URL is https://opensearch.org/community_projects  I love this page, but it's pretty hidden right now.

**Comment by AMoo-Miki** [comment]
nav order change 1

**Comment by AMoo-Miki** [comment]
I feel "Community Projects" would look nicer if it was shortened to just "Projects".

**Comment by CEHENKLE** [comment]
> I feel "Community Projects" would look nicer if it was shortened to just "Projects".

Okay, that works for me.

**Comment by CEHENKLE** [comment]
> Do we have any preference on ordering? My guess would on engagement would be; Blog, Forums, Events, Partners.

You're talking about the subnav for community, right?

That's fine, but where would you put projects?

**Review by CEHENKLE — APPROVED** [review]

**Comment by krisfreedain** [comment]
I love this @AMoo-Miki ! -- I'd like to change the order of the 'Community' drop-down to: Blog, Forum, Events, Partners, Projects. 

I had a couple other question;
- under 'About', I assume 'OpenSearch' links to the About page? (which is perfect, but wanted to confirm)
- in the future, will we be able to link the top level of each to a page? (i.e., if we create an overarching 'Community' page will we be able to link to that? (something I've been thinking about for some time, no plans yet and not a show-stopper, just wanted to ask) 

thank you for all your work on this!

**Comment by AMoo-Miki** [comment]
@krisfreedain 

> I love this @AMoo-Miki ! 

I am glad it is to your liking :)

> I'd like to change the order of the 'Community' drop-down to: Blog, Forum, Events, Partners, Projects.

"Partners" is a top level menu item right now; do you want to move it under "Community"?
Also, you missed the "Community Projects" in the "Community" menu.

>  under 'About', I assume 'OpenSearch' links to the About page? (which is perfect, but wanted to confirm)

Yep.

>  in the future, will we be able to link the top level of each to a page? (i.e., if we create an overarching 'Community' page will we be able to link to that? (something I've been thinking about for some time, no plans yet and not a show-stopper, just wanted to ask)

Yes. By setting a value for `url` of the top level item, it will be a proper hyperlink.

> thank you for all your work on this!

My pleasure.

**Comment by CEHENKLE** [comment]
Hey folks!  Please add any additional comments by Friday EOD.  Hoping to push these changes out Monday (7/18)

**Comment by AMoo-Miki** [comment]
The commit above makes the top nav look like:
Screen Shot 2022-07-14 at 7 36 52 PM

**Comment by krisfreedain** [comment]
@AMoo-Miki perfect! Let's go with it.

**Review by krisfreedain — APPROVED** [review]
Looks great - thanks @AMoo-Miki

**Pull request merged**
