### PR TITLE
[OSCI] Add new author Nicholas Ung

### PR DESCRIPTION
**Pull request by nung22**
### Description
Adds new author nung
 
### Issues Resolved
None

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by cwperks — CHANGES_REQUESTED** [review]
Hi @nung22 , please move this file into the [`authors/osci_2023`](https://github.com/opensearch-project/project-website/tree/main/_authors/osci_2023) folder and update your introduction.

**Comment by joshuarrrr** [comment]
@nung22 Thanks for making changes - now you'll just need to make sure all the commits are signed following the instructions in https://github.com/opensearch-project/project-website/pull/2091/checks?check_run_id=17061290911

**Comment by nung22** [comment]
> @nung22 Thanks for making changes - now you'll just need to make sure all the commits are signed following the instructions in https://github.com/opensearch-project/project-website/pull/2091/checks?check_run_id=17061290911

Got it @joshuarrrr, just updated signed them all off!

**Review by dtaivpp — APPROVED** [review]
Looks great! Also, I love policy engine!

**Pull request merged**
