### PR TITLE
Create 2022-02-10-Getting-Started-with-Fluentd-and-OpenSearch.md

### PR DESCRIPTION
**Pull request by brijos**
### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

Signed-off-by: Joshua Bright <jdbright@amazon.com>

### CODE REVIEW

**Review by brijos — COMMENTED** [review]
There is an ask to be more specific about how we talk about OpenSearch...

The OpenSearch project is, a community-driven, open source search and analytics suite derived from Apache 2.0 licensed Elasticsearch 7.10.2 & Kibana 7.10.2.

**Comment by stockholmux** [comment]
@brijos looks like you're DCO check failed - did you sign off the commits?

**Comment by brijos** [comment]
> 

@jkowall A FluentBit update is in the works.

**Comment by brijos** [comment]
> @brijos looks like you're DCO check failed - did you sign off the commits?

I wasn't for sure how to do it.  Added!

**Pull request closed without merging**
