### PR TITLE
Add KMW Technology to partner page

### PR DESCRIPTION
**Pull request by kwatters**
### Description
We would like to be listed on the OpenSearch partner page.
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by stockholmux** [comment]
Hey @kwatters! Thanks for the request to join our partner program! 

A few things:
1. Generally, we like to see something indicating that you support OpenSearch in your offering (e.g. blog post, documentation, web copy, etc.). I saw Elasticsearch on your site but nothing about OpenSearch. 
2. When trying to go to your site I get a "NET::ERR_CERT_DATE_INVALID" / Privacy Error
3. Something is odd about your commit - it's showing that you change 76 files. Do you need to rebase or something?

Adding @brijos who helps work with this program.

**Review by stockholmux — APPROVED** [review]
LGTM!

**Comment by kwatters** [comment]
Thank you!

**Comment by stockholmux** [comment]
Glad to help @kwatters!

**Pull request merged**
