### PR TITLE
Fixing new file location to account for new partner page in pr-maker …

### LINKED ISSUE #1606: [BUG]New Partner page "Create PR" button links to wrong spot.
**Describe the bug**

The "Create PR" button on https://opensearch.org/new-partner.html links to the github editor with a new file open in _community_projects instead of _partners.

**To Reproduce**
1. Go to 'https://opensearch.org/new-partner.html'
2. Click on 'Create PR'
3. Note it opens the editor with a new file template inside of `_community_projects` instead of `_partners`

**Expected behavior**
Should make a new file in `_partners`

**Screenshots**
image

### PR DESCRIPTION
**Pull request by nateynateynate**
…mod.

### Description
Changes the destination of the new file started by the prmaker mod when clicking 'Create PR' on the new partners page.

### Issues Resolved
#1606 

### Check List
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by nateynateynate** [comment]
It leaves the functionality intact for the previous incarnation, but will act differently for the specific element ID I've used on our new partner page.

**Comment by krisfreedain** [comment]
tested local and new-partner still looks like it is trying to create a PR on _community_projects

**Comment by nateynateynate** [comment]
> tested local and new-partner still looks like it is trying to create a PR on _community_projects

Fixed. Thanks Kris.

**Review by krisfreedain — APPROVED** [review]
LTGM! thanks @nateynateynate

**Pull request merged**
