### PR TITLE
OSCI: Adds new author soumyatanwar

### PR DESCRIPTION
**Pull request by soumyatanwar**
### Description
Adds new author soumyatanwar
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by joshuarrrr — CHANGES_REQUESTED** [review]
@soumyatanwar Please move the new file to the `_authors/osci_2023` directory. Otherwise looks good.

**Comment by soumyatanwar** [comment]
> @soumyatanwar Please move the new file to the `_authors/osci_2023` directory. Otherwise looks good.

Hi @joshuarrrr - Just pushed the changes, can you please review? Let me know in case any other changes are required. Thanks!

**Review by dtaivpp — APPROVED** [review]
Looks good!

**Review by dtaivpp — APPROVED** [review]
LGTM

**Pull request merged**
