### PR TITLE
Titaniam second blog - BYOK for B2B SaaS Operators #647

### LINKED ISSUE #647: BYOK for B2B SaaS Operators
**Describe the blog post your would like to write**
B2B SaaS companies with Opensearch as backend data store can rapidly implement BYOK (Bring your own key)

**What is the title of the blog post?**
BYOK for B2B SaaS Operators

**Who are the authors?**
Pakshi Rajan

**What is the proposed posting date?**
ASAP

### PR DESCRIPTION
**Pull request by pakshi**
### Description
This PR posts Titaniam's second blog - BYOK for B2B SaaS Operators #647
 
### Issues Resolved
#647 

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by stockholmux** [comment]
Hey @pakshi - the PR is failing the DCO check. Can you fix that? [This is a good guide on how to fix it.](https://github.com/src-d/guide/blob/9171d013c648236c39faabcad8598be3c0cf8f56/developer-community/fix-DCO.md#fix-option-2-rebase-git213
)

**Comment by stockholmux** [comment]
@brijos you want to review this blog post?

**Comment by brijos** [comment]
I've reached out to @pakshi for a meeting to have a conversation.

**Comment by pakshi** [comment]
@brijos I added an introduction as we discussed. Can you please check?

@stockholmux there is a good chance I did not get the signed-off right. I will ask my developer to check again.

**Comment by pakshi** [comment]
Creating a new PR

**Pull request closed without merging**
