### PR TITLE
Added Link to the Playground in Navigation. Fix #1073

### LINKED ISSUE #1073: Link to the Playground.
**Is your feature request related to a problem? Please describe.**

We want to draw people to the playgrounds to try our stuff out. 

**Describe the solution you'd like**

We should add a quick link on the upper navbar to link to the playground that says, "Live Demo!" or "Try it out!"

### PR DESCRIPTION
**Pull request by vimalMK**
Signed-off-by: Vimal K <vimalinfo10@gmail.com>

### Description
Added Link to the Playground in Navigation
 
### Issues Resolved
closes #1073 

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by jhmcintyre** [comment]
I like the mockup provided in the issue. My suggestion would be to position the "Live Demo" link as the right-most item rather than left-most. Would like to keep "Download" as the first item in the top nav.

**Comment by vimalMK** [comment]
> I like the mockup provided in the issue. My suggestion would be to position the "Live Demo" link as the right-most item rather than left-most. Would like to keep "Download" as the first item in the top nav.

**Comment by vimalMK** [comment]
> I like the mockup provided in the issue. My suggestion would be to position the "Live Demo" link as the right-most item rather than left-most. Would like to keep "Download" as the first item in the top nav.

Will patch the PR with the position update.

**Comment by dimwetoth** [comment]
I'm a fan of this in general and just pinged our product leader to have someone jump in and talk about when/where.  Thanks for the suggestion.

**Comment by nateynateynate** [comment]
@vimalMK - looks like you're good to go. Let's follow @jhmcintyre 's advice and move it to the right of the navbar so that Download is still first, and I'll start poking @krisfreedain without mercy until it's live. 

Thanks for contributing! This stuff really does make me all warm and fuzzy. :-)

**Review by nateynateynate — APPROVED** [review]
LGTM.

**Comment by vimalMK** [comment]
> @vimalMK - looks like you're good to go. Let's follow @jhmcintyre 's advice and move it to the right of the navbar so that Download is still first, and I'll start poking @krisfreedain without mercy until it's live.
> 
> Thanks for contributing! This stuff really does make me all warm and fuzzy. :-)

Patch added. happy to be a part of this. :)

**Review by nateynateynate — APPROVED** [review]
LGTM. Let's make it happen capn'!

**Comment by dimwetoth** [comment]
Quick note, we do share a top navigation in common with the Docs repository, @nateynateynate is filing an identical PR over there and will merge. Stand by.

**Review by krisfreedain — APPROVED** [review]
thanks @vimalMK! We appreciate this addition to the site and will push it live today - glad this gets Playground out on the navigation. To be fully transparent, we are working on a number of redesigns for the website so this may eventually move to another position, but we'll work to keep everyone updated on that as well - maybe you'll be interested to assist with that change also. Thanks again!

**Comment by vimalMK** [comment]
> thanks @vimalMK! We appreciate this addition to the site and will push it live today - glad this gets Playground out on the navigation. To be fully transparent, we are working on a number of redesigns for the website so this may eventually move to another position, but we'll work to keep everyone updated on that as well - maybe you'll be interested to assist with that change also. Thanks again!

@krisfreedain Your welcome :)  I would love to be part of the redesigns for the website. Pull me in anytime. Thank you

**Pull request merged**
