### PR TITLE
Add Fluent Community Meetups to event calendar

### PR DESCRIPTION
**Pull request by erikbledsoe**
### Description
Adds two upcoming Fluent Community Meetups to the event calendar
 
### Issues Resolved
N/A

### Check List
- [Y] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by pajuric** [comment]
@krisfreedain @dtaivpp - please advise on what needs to be done here.

**Comment by dtaivpp** [comment]
Hey @erikbledsoe can you follow this guide to fix the DCO for your pull request? https://github.com/opensearch-project/project-website/pull/1436/checks?check_run_id=11969814759

**Comment by krisfreedain** [comment]
thanks @erikbledsoe looks like DCO wasn't coming through still so I've resolved that myself as part of PR https://github.com/opensearch-project/project-website/pull/1475

**Comment by erikbledsoe** [comment]
Thanks @krisfreedain. I'll try to get my DCO issue figured out before I submit the next meetings to the calendar. Sorry for the trouble.

**Comment by krisfreedain** [comment]
No worries @erikbledsoe - happy to list your events on the site!

**Pull request closed without merging**
