### PR TITLE
Add nmslib and lucene dashboard to website

### LINKED ISSUE #2871: Embed vectorsearch workload for lucene and nmslib to website
**Is your feature request related to a problem? Please describe.**
Similar to faiss engine, website should show nightly runs metrics for other two engines

**Describe the solution you'd like**
Embed links from benchmarks.opensearch.org and add it to existing list

**Describe alternatives you've considered**
N/A

**Additional context**
Related to https://github.com/opensearch-project/project-website/pull/2850

### PR DESCRIPTION
**Pull request by VijayanB**
### Description
Use share-> Embed code to copy dashboards from https://benchmarks.opensearch.org/ to  be available as part of website
 
### Issues Resolved
#2871

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by rishabh6788 — APPROVED** [review]
LGTM!
@nateynateynate Can you please approve and merge this PR?

**Comment by rishabh6788** [comment]
@AMoo-Miki Can you please help us approving and merging this PR?

**Comment by VijayanB** [comment]
Can i get review for this? Thanks

**Review by nateynateynate — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
