### PR TITLE
[OSCI]: add author skollryu md

### PR DESCRIPTION
**Pull request by SkollRyu**
### Description
Add a markdown page for myself
 
### Issues Resolved
N/A

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by ashwin-pc — CHANGES_REQUESTED** [review]
@SkollRyu  can you move this file to `_authors/osci_2023`? Sorry there was an error in my notes.

**Comment by SkollRyu** [comment]
@ashwin-pc resolved. Please Check. Thanks

**Review by joshuarrrr — APPROVED** [review]
LGTM

**Review by dtaivpp — APPROVED** [review]
Awesome!

**Pull request merged**
