### PR TITLE
[OSCI] Adds new author nbhagat

### PR DESCRIPTION
**Pull request by bobbane11**
### Description
Adds new author nbhagat
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by joshuarrrr — CHANGES_REQUESTED** [review]
@bobbane11 Please move the new file to the `_authors/osci_2023` directory. Otherwise looks good.

**Comment by bobbane11** [comment]
> @bobbane11 Please move the new file to the `_authors/osci_2023` directory. Otherwise looks good.

Ok. I think I fixed it. Can you check?

**Comment by dtaivpp** [comment]
@bobbane11 I am still not seeing it. Check and ensure you have committed the changes and pushed them. Thank you!

**Comment by bobbane11** [comment]
> @bobbane11 I am still not seeing it. Check and ensure you have committed the changes and pushed them. Thank you!

Ok, I think I forgot to push it. Can you check now? Thanks.

**Comment by dtaivpp** [comment]
Closing as we are past deadline and there are outstanding changes.

**Pull request closed without merging**
