### PR TITLE
[OSCI] kmcarranza - Update to Authors file

### PR DESCRIPTION
**Pull request by kmcarranza**
### Issues Resolved
First PR to be merged

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by ashwin-pc — CHANGES_REQUESTED** [review]
@kmcarranza can you move this file to `_authors/osci_2023`? Sorry there was an error in my notes.

**Comment by kmcarranza** [comment]
> @kmcarranza can you move this file to `_authors/osci_2023`? Sorry there was an error in my notes.

I have moved the file. Please let me know if anything additional to update. Thank you.

**Review by joshuarrrr — APPROVED** [review]
LGTM

**Review by dtaivpp — APPROVED** [review]
Looks great!

**Pull request merged**
