### PR TITLE
[OSCI] Add new OSCI author arnoldtingsu 

### PR DESCRIPTION
**Pull request by ArnoldTingSu**
### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ x ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by ashwin-pc — APPROVED** [review]
LGTM :)

**Review by cwperks — APPROVED** [review]
LGTM! 🚢

**Comment by ArnoldTingSu** [comment]
thank you

**Review by dtaivpp — APPROVED** [review]
Thank you!

**Pull request merged**
