### PR TITLE
A typo

### PR DESCRIPTION
**Pull request by behzod**
### Description
Fixing just a simple typo.
 
### Issues Resolved
Fixing just a simple typo: `read_only_inded_level` -> `read_only_index_level`

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by dblock — APPROVED** [review]
thanks!

**Comment by dblock** [comment]
Could you please amend your commit with `-s`, DCO check is failing?

**Comment by behzod** [comment]
> Could you please amend your commit with `-s`, DCO check is failing?

done

**Comment by stockholmux** [comment]
thanks @behzod!

**Pull request merged**
