### PR TITLE
Partner page enhancements 1345

### PR DESCRIPTION
**Pull request by astephanus**
### Description
Adds new Partner Page as discussed in https://github.com/opensearch-project/project-website/issues/1345.
Adds corresponding meta data for varios partners.
 
### Issues Resolved
https://github.com/opensearch-project/project-website/issues/1392
https://github.com/opensearch-project/project-website/issues/1411
https://github.com/opensearch-project/project-website/issues/1412
https://github.com/opensearch-project/project-website/issues/1413
https://github.com/opensearch-project/project-website/issues/1414
https://github.com/opensearch-project/project-website/issues/1415
https://github.com/opensearch-project/project-website/issues/1422
https://github.com/opensearch-project/project-website/issues/1424
https://github.com/opensearch-project/project-website/issues/1425
https://github.com/opensearch-project/project-website/issues/1426
https://github.com/opensearch-project/project-website/issues/1427
https://github.com/opensearch-project/project-website/issues/1439
https://github.com/opensearch-project/project-website/issues/1440
https://github.com/opensearch-project/project-website/issues/1442
https://github.com/opensearch-project/project-website/issues/1445
https://github.com/opensearch-project/project-website/issues/1447
https://github.com/opensearch-project/project-website/issues/1451
https://github.com/opensearch-project/project-website/issues/1464
https://github.com/opensearch-project/project-website/issues/1462
https://github.com/opensearch-project/project-website/issues/1467
https://github.com/opensearch-project/project-website/issues/1471
https://github.com/opensearch-project/project-website/issues/1345 - partial resolution as there is still the need to add new data for partners.

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by krisfreedain — CHANGES_REQUESTED** [review]
thanks @astephanus! Can you please remove the Gemfile and Gemfile.lock from this PR? Those changes should only be necessary with your local Jekyll installation. 

Also, please ensure you submit with DCO - let @nateynateynate @dtaivpp or I know if you need assistance with that.

**Comment by krisfreedain** [comment]
Thanks @astephanus! @nateynateynate - want to give this a whirl locally?

**Review by nateynateynate — APPROVED** [review]

**Comment by krisfreedain** [comment]
@astephanus @nateynateynate - how are we doing on this one? Do we feel like we'll be ready to publish the changes in the next couple days?

**Comment by krisfreedain** [comment]
@astephanus - GitHub is stating we have 2 conflicts on this

Screen Shot 2023-03-30 at 4 38 30 PM

This one:

Screen Shot 2023-03-30 at 4 39 00 PM

and this file:

Screen Shot 2023-03-30 at 4 39 12 PM

Can you look into those and resolve? If everything is ready, I'd like to push this out live on Friday, March 31st! 
thanks again

**Comment by astephanus** [comment]
> @astephanus - GitHub is stating we have 2 conflicts on this
> 
> Screen Shot 2023-03-30 at 4 38 30 PM
> 
> This one:
> 
> Screen Shot 2023-03-30 at 4 39 00 PM
> 
> and this file:
> 
> Screen Shot 2023-03-30 at 4 39 12 PM
> 
> Can you look into those and resolve? If everything is ready, I'd like to push this out live on Friday, March 31st! thanks again

@krisfreedain The conflicts are resovled.

**Review by krisfreedain — APPROVED** [review]
amazing work @astephanus!!! thank you

**Pull request merged**
