### PR TITLE
V1 2 4

### PR DESCRIPTION
**Pull request by stockholmux**
### Description
- Adds version file for 1.2.4
- Adds artifacts files for 1.2.4  (freebsd artifacts are hidden with `_`)
- Adds automation to generate versions files
- Renames artifact automation script to hide from Jekyll

### Issues Resolved
n/a

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
@stockholmux @elfisher Are we supposed to release freebsd version only after other artifacts are out to public?
Should we remove the freebsd files until then?
Thanks.

**Comment by stockholmux** [comment]
@peterzhuamazon The FreeBSD folks need to take some actions before a version is available. In this update, the FreeBSD files are added, but they are hidden from rendering (`_` at the start of a file is ignored by Jekyll).

So, when FreeBSD is ready, they just need to rename the file.

**Review by peterzhuamazon — CHANGES_REQUESTED** [review]
Thanks.

**Review by peterzhuamazon — APPROVED** [review]
Thanks.

**Pull request merged**
