### PR TITLE
Adding author bio 

### PR DESCRIPTION
**Pull request by canascar**
### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by joshuarrrr — APPROVED** [review]
LGTM

**Review by dtaivpp — CHANGES_REQUESTED** [review]
Hey, two requests before we approve, can you move your bio from the `_authors` to the `_authors/osci_2023` and remove the picture? Thank you!

**Comment by canascar** [comment]
@dtaivpp is everything good for this bio to be merged? Thx!

**Comment by kgcreative** [comment]
> Hey, two requests before we approve, can you move your bio from the `_authors` to the `_authors/osci_2023` and remove the picture? Thank you!

@dtaivpp + @joshuarrrr -- Carlos is a UX Designer in the OpenSearch UX team, not an OSCI contributor.

@canascar -- please revert the changes that remove the author photo & move the folder.

**Comment by canascar** [comment]
@dtaivpp reverted last commit due to unnecessary change.

**Comment by apasun** [comment]
Checking in on this? https://github.com/opensearch-project/project-website/pull/2181 (lmk where you are blocked)

Am trying to add you in on this: https://github.com/opensearch-project/project-website/issues/1904

**Comment by kgcreative** [comment]
@dtaivpp or @nateynateynate can we merget his soon? Tis is needed for #1904

**Review by dtaivpp — APPROVED** [review]
Looks good

**Pull request merged**
