### PR TITLE
Removed Opster since they are part of another company now

### PR DESCRIPTION
**Pull request by jkowall**
Since they are part of a commercial entity that is not part of the OpenSearch ecosystem they have stepped back from the community per @segalziv 

### Description
Removes partnership page for Opster
 

### Check List
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Comment by dtaivpp** [comment]
Feels wrong given their contributions to OpenSearch but we don't have a mechanism to move them to emeritus. I'll review this today thanks!

**Comment by krisfreedain** [comment]
Before we do this, we would need to ensure @segalziv voice is captured in this conversation

**Comment by jkowall** [comment]
We should keep the authors and people there, but the company no longer exists and is part of Elastic since the deal is closed. 

image

**Review by dtaivpp — APPROVED** [review]
Looks good

**Pull request merged**
