### PR TITLE
New author file created

### PR DESCRIPTION
**Pull request by YiLin1818**
### Description
[Added new author file for Yi Lin Yang]
 
### Issues Resolved
[]

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by joshuarrrr — CHANGES_REQUESTED** [review]
@YiLin1818 Please move the new file to the _authors/osci_2023 directory and remove all `<>` brackets and the `twitter` field if not using.

**Comment by dtaivpp** [comment]
@YiLin1818 please check Josh's comments and update, thank you!

**Comment by YiLin1818** [comment]
I've made the appropriate changes in the pull request: Chore/add-author-YiLin1818. The final commit should be: @YiLin1818
[Made changes to author file OSCI](https://github.com/opensearch-project/project-website/pull/2217/commits/89284b9843542b24fa5af59ef566285beb85ad4c)

**Comment by dtaivpp** [comment]
Closing as finished in #2217

**Pull request closed without merging**
