### PR TITLE
Adding a new author

### PR DESCRIPTION
**Pull request by AkshathRaghav**
### Description
Added a new author: Akshath Raghav Ravikiran
 
### Issues Resolved
None. 

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by cwperks — APPROVED** [review]
LGTM! 🚢 

**Edit:** The file looks good to me, but please move folders.

**Comment by cwperks** [comment]
@AkshathRaghav Can you please move this to the `_authors/osci_2023/` folder?

**Comment by AkshathRaghav** [comment]
Hi @cwperks, could you check now? Apologies for forgetting to do that!

**Comment by joshuarrrr** [comment]
@AkshathRaghav Thanks for making the fix. You'll also need to fix the signoff on all commits - see instructions in https://github.com/opensearch-project/project-website/pull/2120/checks?check_run_id=17026113583

**Comment by AkshathRaghav** [comment]
Hi @joshuarrrr, apologies for prolonging this issue. I rebased the branch and signed off on the commits. 
Hope everything is alright now!

**Review by dtaivpp — APPROVED** [review]
Approved!

**Pull request merged**
